export const LOGOUT = 'LOGOUT'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const SELECT_COURSE = 'SELECT_COURSE'
export const UNSELECT_COURSE = 'UNSELECT_COURSE'
export const SYNC_FILTERED = 'SYNC_FILTERED'
export const REMOVE_ALL_FILTERS = 'REMOVE_ALL_FILTERS'
export const EDIT_COURSE = 'EDIT_COURSE'
export const FILTER_COURSE_GRID = 'FILTER_COURSE_GRID'
export const DELETE_COURSE = 'DELETE_COURSE'

export const UPDATE_CREATE_COURSE = 'UPDATE_CREATE_COURSE'
export const UPDATE_COURSE_PROP = 'UPDATE_COURSE_PROP'

export const LOADING = 'LOADING'